# >>> meta info
model_name = 'bert_rnn'

# >>> environment
seed = 1

# >>> model
hidden_size = 768
filter_sizes = [2, 3, 4]
num_filters = 256
dropout = 0.1
num_classes = 2
num_layers = 2

# >>> training
epochs = 3
batch_size = 128
pad_size = 32
base_lr = 5e-5
warmup = 0.05

# >>> data
data_root = 'dataset'
train_dir = 'dataset/train'
val_dir = 'dataset/test'
test_dir = 'dataset/test'
