# >>> meta info
model_name = 'ernie'

# >>> environment
seed = 1

# >>> training
epochs = 3
batch_size = 128
pad_size = 32
base_lr = 5e-5
warmup = 0.05

# >>> data
train_dir = 'dataset/augmented/train'
val_dir = 'dataset/augmented/test'
test_dir = 'dataset/augmented/test'

# >>> custom
work_dir = 'work_dir/ernie'
